### ISSUE TITLE
cannot see cursor while editing boot line via "e"

### ISSUE THREAD

**Issue by crysman** [isantop/kernelstub#31]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
kernelstub:
  Installed: 3.1.4~1613405111~20.10~c58b5cb
  Candidate: 3.1.4~1613405111~20.10~c58b5cb
  Version table:
 *** 3.1.4~1613405111~20.10~c58b5cb 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
cannot see cursor while editing boot line via "e" :(

**Steps to reproduce (if you know):**
reboot, press "e" to edit boot parameters, move cursor by left and right arrows - cursor cannot be seen

**Expected behavior:**
cursor functional

**Other Notes:**
editing the line without cursor is a real pain :(

**Comment by isantop** [comment]
Kernelstub does not draw the menu during boot, that's handled by systemd-boot. Please file this issues against that here: https://github.com/systemd/systemd/issues
